# Generated by Django 3.2 on 2021-05-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resources',
            field=models.CharField(blank=True, default='', help_text='Where can the excerpt be found? Provide links, books, titles etc. if any.', max_length=250),
        ),
    ]
